apiVersion: v1
kind: Template
metadata:
  annotations:
    description: 1&1 Ubuntu 16 Base Image
  creationTimestamp: null
  name: ubuntu-16
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying ubuntu-16 base image (testing only)
    labels:
      service: ubuntu-16
    name: ${APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          test: 'Where does this value end up? #196'
        labels:
          name: ${APP_SERVICE_NAME}
          service: ubuntu-16
        name: ${APP_SERVICE_NAME}
      spec:
        containers:
        - env:
          image: 1and1internet/ubuntu-16:unstable
          imagePullPolicy: Always
          name: ${APP_SERVICE_NAME}
        restartPolicy: Always
        securityContext:
          runAsUser: 1021400022
    triggers:
    - type: ConfigChange
parameters:
- description: Application service name
  displayName: Application service name
  name: APP_SERVICE_NAME
  required: true
  from: ubuntu-16-[a-z]{5}
  generate: expression

